name: Main

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@main
      - uses: bahmutov/npm-install@v1
      - run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    steps:
      - run: echo "Work in progress"
